export const ROUTES = {
  LOGIN: "/login",
  HOME: "/home",
  USERS: "/users",
  OBSERVATION_NEW: "/observation/new",
  HEATMAP: "/heatmap",
  PREDICTIVE_ROUTES: "/predictive-routes",
  MY_OBSERVATIONS: "/my-observations",
  DATA_LOAD: "/data-load",
  VARIABLES_CONFIG: "/variables-config",
  RULES_EDITOR: "/rules-editor",
  EXECUTION: "/execution",
  VALIDATION: "/validation",
  GEOGRAPHIC_AUDIT: "/geographic-audit",
  CALIBRATION: "/calibration",
  SIMULATION_HISTORY: "/simulation-history",
  EXECUTIVE_DASHBOARD: "/executive-dashboard",
  MAP_VIEWER: "/map-viewer",
  SCENARIO_COMPARATOR: "/scenario-comparator",
  REPORTS: "/reports",
  APPROVAL: "/approval",
} as const
